### ISSUE TITLE
User Activity - mark/unmark a post as spam

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-vue#11]

**Comment by Novusphere** [comment]
t ack

**Comment by dblstacker** [comment]
I can mark a post as spam but I'm not sure how to unmark.

**Comment by bluabaleno** [comment]
no option to see posts marked as spam, so no way to un-mark it from UI

**Comment by Novusphere** [comment]
You can disable it by going into your settings and disable "hide spam content" which is on by default. I agree we need a page to show all the posts you've marked as spam. I've opened #67 for that so continue discussion there.
