### ISSUE TITLE
Follow confirmation message 

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-vue#115]
![ezgif-2-834e60ee81cf](https://user-images.githubusercontent.com/14120416/87484963-7ceeaa80-c62f-11ea-90a9-f8aa2ecb0bf0.gif)

It would be better to have a check as a confirmation instead of the window(?) disappearing right away.

**Comment by Novusphere** [comment]
why? isn't this just adding more steps/clicks to the UX?

**Comment by dblstacker** [comment]
I like the way that twitter does it. Click follow and the button that you clicked changes color and turns into "following".
