### ISSUE TITLE
Show replies from users you've follow on Feed. 

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-vue#116]
Along with the title of the post they're replying to.

<img width="520" alt="Screen Shot 2020-07-15 at 2 11 10 PM" src="https://user-images.githubusercontent.com/14120416/87548917-15734200-c6a5-11ea-9f79-56bbf14dc279.png">

So in the scenario above, if I had followed cryptodb, his reply to the top level post will show as the only comment and the top level thread is shown as a collapsed post by default.

**Comment by bluabaleno** [comment]
Same for mobile, just without the ability to expand the post via the collapse button.

**Comment by Novusphere** [comment]
how do we handle replies to other replies, i.e. not the thread itself

**Comment by Novusphere** [comment]
all are handled as OP > reply
