### ISSUE TITLE
linking to a blog post should take you to the user's profile card and not the #blog card.

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-vue#119]
weird wording, will clarify.

So this is my blog post:
https://discussions.app/tag/blog/3ra9kjgxzm828/blogs_bots_feeds_and_going_on_tv

But when someone lands on the blog it shows the #blog on top when it should really be showing my profile.

expected behavior:
<img width="951" alt="Screen Shot 2020-07-16 at 1 22 51 PM" src="https://user-images.githubusercontent.com/14120416/87670346-7a8f6c00-c767-11ea-954e-04c329c8c870.png">

current behavior:
<img width="951" alt="Screen Shot 2020-07-16 at 1 22 42 PM" src="https://user-images.githubusercontent.com/14120416/87670427-9abf2b00-c767-11ea-8fe7-d7d747c4916f.png">

**Comment by bluabaleno** [comment]
Missing info and option to follow 
<img width="857" alt="Screen Shot 2020-07-18 at 10 53 25 PM" src="https://user-images.githubusercontent.com/14120416/87862577-8f2b5a00-c949-11ea-992a-4c989ad38cef.png">

@Novusphere

**Comment by Novusphere** [comment]
You don't see the follow button for yourself. By info, do you mean the number of followers the user has? @bluabaleno
