### ISSUE TITLE
Add (or accurately) keep the submit button on both editor/preview tab

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-vue#120]
![F94E6737-D838-4196-9FE2-E5E270D4077D](https://user-images.githubusercontent.com/14120416/87731287-0a620400-c7c2-11ea-8f65-07eeb7499fb8.png)
![FC26CDB1-6878-43DA-BC91-7CB0F523A822](https://user-images.githubusercontent.com/14120416/87731291-0cc45e00-c7c2-11ea-8bb0-1b350222cf38.png)

See GitHub issue submission box

**Comment by Novusphere** [comment]
Ok, so just to clarify, the submit button should be visible regardless of whether you're in the "Write" or "Preview" tab. This is what you're asking for, yes?
