### ISSUE TITLE
bring up profile card when clicking on a users who have been mentioned.

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-vue#122]
<img width="524" alt="Screen Shot 2020-07-18 at 10 55 21 PM" src="https://user-images.githubusercontent.com/14120416/87862606-cac62400-c949-11ea-9612-a0c0563f3bdb.png">
Instead of taking the user to their profile right away, it should offer the same profile card that pops up when clicking on the username on the front page.

**Comment by Novusphere** [comment]
I'm going to have to rework how that works a bit to implement this, but I assume you want the same thing done for hashtags too? @bluabaleno
