### ISSUE TITLE
"raindrop" feature

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-vue#134]
Implement raindrop feature to perform an airdrop to everyone that has participated in a given thread

**Comment by bluabaleno** [comment]
should we have a notification to go with this?

"Someone just made it rain in your thread!"

"You got rained on!"

etc

**Comment by Novusphere** [comment]
@bluabaleno The notification would be the tip itself... so it can say whatever in the memo.

**Comment by bluabaleno** [comment]
The option to trigger raindrop, how should that be handled? should it be from the post menu, the three dots? Or a reply comment?
