### ISSUE TITLE
Make tipped tokens clickable.

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-vue#148]
If someone tipped you some atmos, you should be able to click on the atmos icon and find out more about ATMOS

<img width="535" alt="Screen Shot 2020-07-29 at 10 37 42 PM" src="https://user-images.githubusercontent.com/14120416/88856286-21eeb300-d1ec-11ea-88f1-f7193834b9f6.png">

**Comment by Novusphere** [comment]
So... should this open the ATMOS community card or what?

**Comment by bluabaleno** [comment]
> So... should this open the ATMOS community card or what?

Ah I was think it would open the page but no, opening the community card is a much better idea.
