### ISSUE TITLE
Scrolling UX issue with Safari in Thread Dialog

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-vue#158]
@bluabaleno please describe to best of your ability and/or include any recordings

**Comment by bluabaleno** [comment]
when opening a short post, i.e a post that can be view in full without scrolling, initiating the scrolling sequence would scroll down the background.

**Comment by Novusphere** [comment]
note: maybe related? https://github.com/vuetifyjs/vuetify/issues/3875

**Comment by Novusphere** [comment]
Fixed in https://github.com/Novusphere/discussions-vue/commit/ff73c12765934a385eb9aa1d4a41b056f39b464a
