### ISSUE TITLE
User Profile - browse blog posts

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-vue#17]

**Comment by Novusphere** [comment]
t ack - probably the only profile with a "#blog" post https://gamma.discussions.app/u/xia256-EOS5FcwE6haZZNNTR6zA3QcyAwJwJhk53s7UjZDch1c7QgydBWFSe

**Comment by bluabaleno** [comment]
t ack 

definitely need a better UI for posting to blog thou
