### ISSUE TITLE
personalized icon for Mr.T

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-vue#218]
![d3pSTnWl jpg-medium](https://user-images.githubusercontent.com/14120416/92387111-e7dad000-f10c-11ea-8b82-8ea29a373dd8.jpeg)

**Comment by Novusphere** [comment]
You don't need me to do this: https://github.com/Novusphere/discussions-app-settings/blob/master/publickeyicons.json

Personally though, I am against this and we should stop doing it for people not associated with the team.
