### ISSUE TITLE
Price Feed Refinement 

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-vue#246]
displaying 24hr percentage change:

ATMOS +2.50% with % centered relative to the bigger text (ATMOS)

**Comment by Novusphere** [comment]
# Notes for Developer

Component: AssetCard.vue
The field with the data: `change24`

**Comment by bluabaleno** [comment]
Can we try to add it under the price data? Might make the card a bit bigger but would be the easiest way forward
