### ISSUE TITLE
General - discover communities

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-vue#25]

**Comment by Novusphere** [comment]
t ack

**Comment by bluabaleno** [comment]
t ack 

also, small UI issue:
<img width="723" alt="Screen Shot 2020-07-06 at 10 24 21 AM" src="https://user-images.githubusercontent.com/14120416/86577951-ef49f580-bf72-11ea-9549-8289c7b6165f.png">

**Comment by Novusphere** [comment]
fixed in https://github.com/Novusphere/discussions-vue/commit/bc335798ad30acddb90f4cf88f66048e763a4f6e
