### ISSUE TITLE
Change EOSGO to Logo aligned with the text in Wallets/Assets

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-vue#251]
![EOS GO credit](https://user-images.githubusercontent.com/14120416/93765807-62c3e080-fc0d-11ea-8d8f-d5b90e62a3b6.jpg)
Link to http://eosgo.io

**Comment by Novusphere** [comment]
![image](https://user-images.githubusercontent.com/39639828/93814942-403cc200-fc23-11ea-8f35-bf841aefc00d.png)

**Comment by bluabaleno** [comment]
Can we replace the text with their logo?
![1*x3s3ayV5zZi8nI5PMfHgYA-2](https://user-images.githubusercontent.com/14120416/93898257-ed2e4200-fcea-11ea-8928-4c56b37db358.jpeg)

**Comment by bluabaleno** [comment]
Now that I had another look at it after some time, for a new users/content creator it's the EOS value of the tokens is sort of meaningless

I'm still oppose to displaying the dollar amount on posts, but I think for the wallet that's not a bad idea.

**Comment by Novusphere** [comment]
Basically another case of the image isn't nicely oriented to be used in the same line as text so while I know exactly what you want, spending on the time on it doesn't really seem the best use of time. An easier solution to this is if they are the ones who want this to just get a single image that says "Price feed provided by EOSGO" or something more generic might be "powered by EOSGO".

I'll leave this issue open but tagging wontfix.

**Comment by Novusphere** [comment]
Also I don't quite get what your second comment is saying. Do you want the EOS price removed and instead for it to display the dollar price? The dollar value of their tokens? Or what?

**Comment by bluabaleno** [comment]
> Also I don't quite get what your second comment is saying. Do you want the EOS price removed and instead for it to display the dollar price? The dollar value of their tokens? Or what?

yeah ATMOS/EOS don't mean much for users outside of EOS.

**Comment by Novusphere** [comment]
Got it, I'll change it to USD then.

**Comment by bluabaleno** [comment]
Will close this issue. Further refinements to be addressed in another issue.
