### ISSUE TITLE
Raindrop tips are not showing up in UI

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-vue#267]
Raindrop post:
https://discussions.app/tag/blog/305tbsjdfvn64/man-haven-done-raindrop-for-loooooong-while-let-make-it-rain-baby

Raindrop trx
https://bloks.io/transaction/4cd01337c1584d4b8f1a33b9d5c747a21e3593bffcea170bfb1432a6cc5fadc1

**Comment by Novusphere** [comment]
This is an issue as a result of introducing Greymass as a history provider. A long term solution to this would be to change how the underlying system works itself and introduce a new field, `metadata` to the UID contract transfer method. I'll take a look into this on the weekend.

**Comment by xia256** [comment]
Closing this issue as it's fixed on the beta build.
