### ISSUE TITLE
Add memo to UID transactions

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-vue#273]
Allowing users to send tips or direct transfers with a short message

**Comment by xia256** [comment]
Does this mean you would like for them to be able to alter the message so instead of it saying: 
`tip to DubDigital for /tag/dubdigital/1ior4ek99bk3f/wanchain-crypto-analysis-wanchain-is-here`

The user has the ability to enter whatever text they want / override?

**Comment by bluabaleno** [comment]
yep, but only if it is done via the profile tip rather than on the post itself
