### ISSUE TITLE
Posts - collapse a comment

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-vue#41]

**Comment by Novusphere** [comment]
t acj

**Comment by bluabaleno** [comment]
not available on mobile?

**Comment by Novusphere** [comment]
I thought we agreed it takes up too much space and isn't really a feature that's needed on mobile?

**Comment by bluabaleno** [comment]
hmmmmm 

I think we agree it took up too much space on the front-page preview, not in the comments. 

Anecdotally I use it a lot on Reddit since there's always long replies, so I imagine it would be good for us to have, plus I don't think it takes up all that much space.

**Comment by Novusphere** [comment]
implemented in https://github.com/Novusphere/discussions-vue/commit/08e119c07ab470fd1bd252871603b1c6a92770ec please review @bluabaleno
