### ISSUE TITLE
Posts - prompt "are you sure?" if user tries to leave pages with some text written

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-vue#44]

**Comment by Novusphere** [comment]
t ack

**Comment by bluabaleno** [comment]
t ack

nice, it always works on mobile. nothing comes up when closing mobile tabs but I guess that's more to do with how the mobile browser work and we can't do anything about that.

**Comment by Novusphere** [comment]
> but I guess that's more to do with how the mobile browser work and we can't do anything about that.

AFAIK, yes @bluabaleno
