### ISSUE TITLE
add / remove moderators

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-vue#52]

**Comment by fixedelineation** [comment]
Sort if works. On desktop I can Add John Lazurus as a mod, but can't change user to anyone else. On Mobile, I can add Jacque but no one else. the moderator box doesn't respond to input or offer an option to type anything in.  I can remove mods. 
<img width="978" alt="Screen Shot 2020-07-06 at 1 09 59 PM" src="https://user-images.githubusercontent.com/17442082/86637284-24157700-bf8a-11ea-925d-bab3395182e1.png">

**Comment by Novusphere** [comment]
@fixedelineation you can only add moderators here from people you're following, otherwise you can do it from their profile. It's not good UX to take user input here since the information we need to add someone as a moderator is their display name and public key. You likely don't know a user's public key and typing it is a disaster.
