### ISSUE TITLE
Change how single post show and new login process

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-vue#58]
[Google doc link ](https://docs.google.com/document/d/1yDFaMgARmMFdRfOlfCSUqL_g_zN06QaIbzW-Ai_QJQU/edit)

**Comment by Novusphere** [comment]
The single post change has been made, regarding

> probably should have a bit of text that says "Don't have an EOS account?" somewhere that redirects them to the EOS account creation page.

this seems like a bad idea. If it's a new account and they don't have an EOS account, how are they going to create one? This only will confuse the user.

**Comment by bluabaleno** [comment]
hmmm yeah that's a good point

**Comment by bluabaleno** [comment]
bump

**Comment by Novusphere** [comment]
Closed, duplicate of #75
