### ISSUE TITLE
User Activity - subscribe/unsubscribe to a tag

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-vue#6]

**Comment by Novusphere** [comment]
t ack

**Comment by dblstacker** [comment]
t ack

**Comment by bluabaleno** [comment]
huh... unsubscribing to a tag removes it from trending, is that a expected behavior?

**Comment by bluabaleno** [comment]
also, sub/unsubbing doesn't seem to carry over from mobile to laptop? or vice versa?

**Comment by Novusphere** [comment]
> also, sub/unsubbing doesn't seem to carry over from mobile to laptop? or vice versa?

accounts don't save currently

**Comment by fixedelineation** [comment]
t ack
