### ISSUE TITLE
settings page for managing following

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-vue#60]
Should you be able to see who a person is following? This dictates where we put the following setting (to see the people your following and unfollow enmass easily)

If you can see who other people are following, then it makes sense to just put ths in the user profile, where anyone can see your following (except you also see an unfollow button)

If not, then it makes sense to stick it in settings

**Comment by fixedelineation** [comment]
I think we should make followers and who you are following similar to twitter so these things should be in profile.

**Comment by Novusphere** [comment]
another suggestion is to have "My Communities" (on the left) be collapsable, as well as a "My following" (or w/e) and by default this is collapsed, but has a list of everyone you're following. This is good for desktop, but doesn't address mobile so we still need a solution for both.

**Comment by Novusphere** [comment]
after discussion, this should be placed in the user profile and should be publicly visible to everyone
