### ISSUE TITLE
VIG not support in the assets cards.

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-vue#66]

**Comment by Novusphere** [comment]
So, this is because the tag often used for vigor "#vigor" is not the same as the symbol for vigor, "VIG" a solution to this may be to explicitly define the symbol in the site.json:

https://github.com/Novusphere/discussions-app-settings/blob/master/site.json#L115

i.e. `"symbol": "VIG"`

**Comment by bluabaleno** [comment]
> "symbol": "VIG"

great idea

**Comment by Novusphere** [comment]
added in https://github.com/Novusphere/discussions-vue/commit/6687a8941b0863bfc66d25b24cff1867f3064ca6
