### ISSUE TITLE
User Activity - connect EOS account

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-vue#8]

**Comment by Novusphere** [comment]
t ack anchor, greymass

**Comment by dblstacker** [comment]
not clear how to connect EOS account. I went to: "wallet", and then "EOS account" but it appears that I'm paying for an EOS account. I'm not sure how I'm supposed to connect via Scatter.

**Comment by Novusphere** [comment]
@dblstacker try withdrawing, you only get asked to connect an EOS account when you're doing something that requires an EOS account (currently). Right now, that only means withdrawals for normal users.

It was more convoluted before that a user had to **first** go into their Settings > Connections and connect a wallet, then go to withdraw.

**Comment by bluabaleno** [comment]
unable to connect via anchor or scatter. I have both open but the drop-down is grayed out for me

**Comment by Novusphere** [comment]
> unable to connect via anchor or scatter. I have both open but the drop-down is grayed out for me

fixed in https://github.com/Novusphere/discussions-vue/commit/d321e4f9accaf358de6b00896d444a7fad1f25fb

please try again

**Comment by bluabaleno** [comment]
t ack

**Comment by dblstacker** [comment]
t ack
