### ISSUE TITLE
Hitting 'enter' key after entering password for tips brings up a close tab warning

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-vue#80]
![ezgif-5-4bbca1cc1636](https://user-images.githubusercontent.com/14120416/86771189-b761b180-c049-11ea-9118-04c3659dc3af.gif)

**Comment by Novusphere** [comment]
fixed in https://github.com/Novusphere/discussions-vue/commit/af3bc351b2e617d51b7ce6dbcd03a90dbc75e01c confirm and close issue @bluabaleno

**Comment by fixedelineation** [comment]
t ack

**Comment by bluabaleno** [comment]
t ack
