### ISSUE TITLE
[macbook] scrolling lag in thread dialog

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-vue#93]
https://atmosdb.novusphere.io/discussions/upload/image/1594232420616.gif

**Comment by fixedelineation** [comment]
t ack didn't notice any lag

**Comment by bluabaleno** [comment]
so I test it in three configurations

On iPhone XR - no lag
On MacBook Pro + Chrome - Jitters
On MacBook Pro + Safari - Stutters

**Comment by Novusphere** [comment]
adding video provided by @bluabaleno : https://www.youtube.com/watch?v=L0zextM-YDI
issue only seems to be with dialog, not with threads itself

**Comment by Novusphere** [comment]
closed for now... may be reopend later under refinement
