### ISSUE TITLE
[safari] Disable redirecting when creating post in editor

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-vue#96]
When I upload an img in the editor, it happens to be possible to click on the img and I'm redirected without warning, wiping away the article I was writing.

![ezgif-2-d07db5484ee1](https://user-images.githubusercontent.com/14120416/87035997-0d695d00-c1e2-11ea-89dc-30929c961ea9.gif)

**Comment by Novusphere** [comment]
note: seems to be a safari only issue, does not occur in chrome/brave/ff
